### ISSUE TITLE
Error: The CA was unable to validate the file you provisioned. 

### ISSUE THREAD

**Issue by Splaktar** [Daplie/letsencrypt-cli#13]
I tried to follow the instructions and I tried a number of different ways of doing it, but they always give me these errors:

```
sudo letsencrypt certonly   --agree-tos --email support@gdgx.io   --standalone   --domains gdgroups.org --config-dir 
~/letsencrypt/etc
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned. 
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105194 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105195 [invalid]
   Could not connect to http://gdgroups.org/.well-known/acme-challenge/sOtrdGxJ3wMc-s30w8mTPaZvuhjVIFSdaJ-IISQbg2U
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105196 [pending]
    at handleErr (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:200:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
[Error]: letsencrypt-cli
Error: The CA was unable to validate the file you provisioned. 
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105194 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105195 [invalid]
   Could not connect to http://gdgroups.org/.well-known/acme-challenge/sOtrdGxJ3wMc-s30w8mTPaZvuhjVIFSdaJ-IISQbg2U
 - https://acme-v01.api.letsencrypt.org/acme/challenge/35Qp1Y3dlhwv0boKkqFWCEupgnqHFbxyLGt_LO3RIXE/142105196 [pending]
    at handleErr (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:200:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

I have no idea how to use these error messages to solve the problem.

**Comment by thomasmeeus** [comment]
Same issue here.. is there a solution/workaround for this?

**Comment by thomasmeeus** [comment]
Apparently this error appears to be triggered because Let's Encrypt is not yet compatible with ipv6. I removed the AAAA record of my domain and the certificate request succeeded.

**Comment by coolaj86** [comment]
Try with v2.0.0, which is a simpler and better-tested code base:
https://github.com/Daplie/letsencrypt-cli

Also closing this issue as there is not enough information to solve the problem.
