### ISSUE TITLE
TypeError: hex is not a function

### ISSUE THREAD

**Issue by JohannesHoppe** [Daplie/letsencrypt-cli#16]
I'm on Windows 8.1, node-gyp installed, openSSL is installed in C:\OpenSSL-Win64\. Evyerthing should be fine. But:

```
letsencrypt certonly --agree-tos --email xxx@xxx.de --standalone --domains test.de --config-dir .

[Error]: letsencrypt-cli
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at _bigIntToBase64Url (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:10:20)
    at Object.module.exports._forgeToPrivateJwk (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:41:10)
    at Object.module.exports.exportPrivateJwk (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-extra.js:105:21)
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:88:47
    at Object.module.exports.generateKeypair (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\lib\rsa-ursa.js:44:5)
    at Object.RSA.generateKeypair (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\rsa-compat\node.js:86:19)
    at Object.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as generateKeypairAsync] (eval at <anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at Object.createAccount (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\lib\accounts.js:16:14)
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\lib\core.js:405:25
    at tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\bluebird\js\release\promise.js:606:10)
```

**Comment by coolaj86** [comment]
This is fixed in v2.0.0, which was just published.
https://github.com/Daplie/letsencrypt-cli

**Comment by JohannesHoppe** [comment]
:+1:

**Comment by JohannesHoppe** [comment]
Error is back in v2.1.1! :disappointed_relieved:

**Comment by coolaj86** [comment]
Hmm... You're on Windows...

This is a problem with `rsa-compat`, not `letsencrypt-clip`.

Let's move the discussion over here https://github.com/Daplie/rsa-compat.js/issues/9 and see if we can solve it.
