### ISSUE TITLE
letsencrypt-cli@2.0.0 --  servers.listen is not a function

### ISSUE THREAD

**Issue by JohannesHoppe** [Daplie/letsencrypt-cli#19]
updated to v2, now i get:

```
letsencrypt certonly --agree-tos --email test@example.org --standalone --domains example.org --config-dir .

C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\lib\servers.js:62
        servers.listen(port, function () {
                ^

TypeError: servers.listen is not a function
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\lib\servers.js:62:17
    at Array.forEach (native)
    at Object.servers.startServers (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\lib\servers.js:58:16)
    at Object.module.exports.run (C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\index.js:28:60)
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\bin\letsencrypt.js:93:20
    at C:\Users\user\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by coolaj86** [comment]
v2.1.1 fixes bug introduced in v2.1.0
