### ISSUE TITLE
TypeError when using CLI

### ISSUE THREAD

**Issue by bhargav175** [Daplie/letsencrypt-cli#3]
I installed letsencrypt-cli globally in npm on an ec2-instance. I followed the steps show. I configured access for port 443 on EC2 as well. 

 When I did this

```bash
sudo  letsencrypt certonly \
  --agree-tos --email myemail@gmail.com \
  --standalone \
  --domains subdomain.mysite.com \
  --server https://acme-staging.api.letsencrypt.org/directory \
  --config-dir ~/letsencrypt/etc
```

I got this error.

```
    Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at /usr/local/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js:124:26
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/index.js:307:13
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/index.js:202:26
    at tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:670:18)
    at Promise._reject (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/bluebird/js/release/promise.js:634:18)

Unhandled rejection Error: The CA was unable to validate the file you provisioned: undefined
    at handleErr (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:350:17)
    at ensureValidation (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:226:16)
    at Request._callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:215:13)
    at Request.self.callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:198:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1035:10)
    at emitOne (events.js:83:20)
    at Request.emit (events.js:170:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:962:12)
    at emitNone (events.js:73:20)
    at IncomingMessage.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

When I tried the same thing without sudo I got this error 

```
     listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at Server.listen (net.js:1370:5)
    at /usr/local/lib/node_modules/letsencrypt-cli/lib/standalone.js:53:51
    at Array.forEach (native)
    at Object.handlers.startServers (/u
```

Is it a bug or did I miss something?

**Comment by coolaj86** [comment]
I didn't properly expose the error message, but the problem appears to be that you haven't allowed access to all of the necessary ports.

Make sure that all of these are let through via TCP:

* 80
* 443
* 5001

**Comment by bhargav175** [comment]
Yeah, that appears to be the case. Thanks!

On Sat, 2 Jan 2016 at 03:38 AJ ONeal <notifications@github.com> wrote:

> I didn't properly expose the error message, but the problem appears to be
> that you haven't allowed access to all of the necessary ports.
>
> Make sure that all of these are let through via TCP:
>
>    - 80
>    - 443
>    - 5001
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Daplie/letsencrypt-cli/issues/3#issuecomment-168340842>
> .
>
-- 
Bhargav Ponnapalli
