### ISSUE TITLE
Error on OS X El Capitan (10.10.3)

### ISSUE THREAD

**Issue by christianhaller** [Daplie/letsencrypt-cli#9]
Hi,
maybe I'm doing it wrong, but a simple 
`letsencrypt certonly --agree-tos --email hallo@christianhaller.com --standalone --domains download-your-travelmap.christianhaller.com --server https://acme-staging.api.letsencrypt.org/directory`

gives me this error

````
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at /usr/local/lib/node_modules/letsencrypt-cli/lib/standalone.js:53:51
    at Array.forEach (native)
    at Object.handlers.startServers (/usr/local/lib/node_modules/letsencrypt-cli/lib/standalone.js:52:18)
    at /usr/local/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js:99:16
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by coolaj86** [comment]
You are doing it wrong.

```
Error: listen EACCES 0.0.0.0:80
```

You have to run the server as root. And it still probably won't work, unless you have NAT forwarding setup on your router.
